### ISSUE TITLE
versionCode

### ISSUE THREAD

**Issue by IzzySoft** [sahej-dev/Snow#10]
A tiny little challenge for free and without extra registration :speak_no_evil: 

Android uses `versionCode` to tell versions apart and recognize an APK as update (or not an update). You explicitly set it to "always `1` [here](https://github.com/sahej-dev/Snow/blob/main/pubspec.yaml#L6):

```yaml
version: 1.2.2+1
```

So when you make a new release, to an Android device the APK will seem to be the very same version that is already installed. Seeing there are 6 releases marked, one would expect the `+1` rather be a `+6` by now. Could you please take care to always increase that number when preparing a new release? That would make it possible to have the app available in stores/repos offering those using them to notify about and install newer versions when they've been released, Thanks in advance!

**Comment by sahej-dev** [comment]
Thanks a lot for pointing that out. I had no idea this is how android handled app updates. Fixing this right now.

Again, thanks a ton!

**Comment by IzzySoft** [comment]
Thanks for the fast fix!

> That would make it possible to have the app available in stores/repos …

Which is now the case. At around 6 pm UTC (or after that), you will find Snow [here in my repo](https://apt.izzysoft.de/packages/com.sahej.snow/); updates should show up there within 24h of your creating a new release and attaching the APK to it (my updater runs daily, will fetch the arm64 build, and keep 2 versions – that's slightly above the 30-MB-limit per-app as per the inclusion criteria, but keeping at least the previous version avoids "file-not-found" when a user wants to install and it was updated "just now").

If you like what you see there:

* be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme
* let me know if I shall send you a PR with the metadata I've set up in [Fastlane format](https://gitlab.com/-/snippets/1895688), so you can be in control how your app is presented
* Enjoy :smiley:

**Comment by sahej-dev** [comment]
Yes, I'd love that. Please do make that PR. I'll be adding the badge too.

PS: I actually use your repo on my personal device through the Driod-ify client and it is an honor to be included.

**Comment by sahej-dev** [comment]
Also I would like to acknowledge you in my Readme for powering app store hosting for Snow. If you'd like me to do that then feel free to share a link to your website/socials.

**Comment by IzzySoft** [comment]
There you go with the Fastlane PR :smiley: As for links to use, take your pick:

* [my repo](https://apt.izzysoft.de/fdroid)
* [my Android website](https://android.izzysoft.de/)
* My Github user (same on GitLab, and just "izzy" at Codeberg)
* My Fediverse account: [\@IzzyOnDroid](https://floss.social/@IzzyOnDroid)

Just giving you something to choose from, no need to include a full bio :see_no_evil:
