### ISSUE TITLE
Add adaptive app icon for Android 13+.

### ISSUE THREAD

**Issue by THElegend5** [sahej-dev/Snow#12]
### Description

Snow currently doesn't have an adaptive icon which makes it stand out from rest of my apps.

### Users

Makes Snow consisitent with rest of  my appd which support adaptive icons.

**Comment by sahej-dev** [comment]
My apologies for a late response. I have been busy finding a job. As I'm still looking for one, it may take a few weeks/months for me to fix this.

I hope you understand.
